/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentska_sluzba;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sc21l
 */
public class ObradaPrijava extends javax.swing.JFrame {

    java.sql.Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    static int brojac=0;
    static int prijava=0;
    static int trig=0;
    String ID_PR,ID_IRK;
    public ObradaPrijava() {
        initComponents();
        this.setLocationRelativeTo(null);
        popuniPredmet();
    }
    
    public void popuniPredmet(){
    
    String sqlSelect="select distinct Naziv from Predmet right join Rokovi on Predmet.ID_P=Rokovi.ID_P ";
    
    try{
            con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
            pst=con.prepareStatement(sqlSelect);
            rs=pst.executeQuery();
            while(rs.next())
            {
                PredmetIR.addItem(rs.getString("Naziv"));
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ImeOP = new javax.swing.JTextField();
        PrezimeOP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        IndeksOP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        IDOP = new javax.swing.JTextField();
        PredmetIR = new javax.swing.JComboBox<>();
        DatumIR = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PretragaID = new javax.swing.JButton();
        PretragaIndeks = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NazadOP = new javax.swing.JButton();
        ListajTabelu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaOP = new javax.swing.JTable();
        DodajS = new javax.swing.JButton();
        ProvjeraDugovanjaOP = new javax.swing.JButton();
        OdjavaOP = new javax.swing.JButton();
        UkloniOP = new javax.swing.JButton();
        OcistiPolja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obrada prijava-Studentska sluzba");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "  Prijava Studenta  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(7, 41, 78))); // NOI18N

        jLabel2.setText("Ime");

        jLabel3.setText("Prezime");

        jLabel4.setText("Indeks");

        jLabel7.setText("ID");

        jLabel5.setText("Predmet");

        jLabel6.setText("Datum");

        PretragaID.setBackground(new java.awt.Color(255, 255, 255));
        PretragaID.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\zoom-search-2-icon.png")); // NOI18N
        PretragaID.setBorderPainted(false);
        PretragaID.setContentAreaFilled(false);
        PretragaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PretragaIDActionPerformed(evt);
            }
        });

        PretragaIndeks.setBackground(new java.awt.Color(255, 255, 255));
        PretragaIndeks.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\zoom-search-2-icon.png")); // NOI18N
        PretragaIndeks.setBorderPainted(false);
        PretragaIndeks.setContentAreaFilled(false);
        PretragaIndeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PretragaIndeksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(IndeksOP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrezimeOP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(ImeOP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PretragaIndeks, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PredmetIR, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(IDOP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(PretragaID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(DatumIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(IDOP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(PretragaID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ImeOP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrezimeOP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(IndeksOP)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PretragaIndeks, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PredmetIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatumIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\apeironLogo.png")); // NOI18N

        NazadOP.setBackground(new java.awt.Color(7, 41, 78));
        NazadOP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NazadOP.setForeground(new java.awt.Color(255, 255, 255));
        NazadOP.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\arrow-back-1-icon.png")); // NOI18N
        NazadOP.setText("Nazad");
        NazadOP.setActionCommand(" Nazad ");
        NazadOP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(54, 89, 147), null, null));
        NazadOP.setBorderPainted(false);
        NazadOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NazadOPActionPerformed(evt);
            }
        });

        ListajTabelu.setBackground(new java.awt.Color(7, 41, 78));
        ListajTabelu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ListajTabelu.setForeground(new java.awt.Color(255, 255, 255));
        ListajTabelu.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\Arrow-inside-2-icon.png")); // NOI18N
        ListajTabelu.setText("Izlistaj prijave");
        ListajTabelu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(54, 89, 147), null, null));
        ListajTabelu.setBorderPainted(false);
        ListajTabelu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListajTabeluActionPerformed(evt);
            }
        });

        TabelaOP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelaOP);

        DodajS.setBackground(new java.awt.Color(7, 41, 78));
        DodajS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DodajS.setForeground(new java.awt.Color(255, 255, 255));
        DodajS.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\add-1-icon.png")); // NOI18N
        DodajS.setText("Dodaj");
        DodajS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(54, 89, 147), null, null));
        DodajS.setBorderPainted(false);
        DodajS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajSActionPerformed(evt);
            }
        });

        ProvjeraDugovanjaOP.setBackground(new java.awt.Color(7, 41, 78));
        ProvjeraDugovanjaOP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ProvjeraDugovanjaOP.setForeground(new java.awt.Color(255, 255, 255));
        ProvjeraDugovanjaOP.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\Bank-icon.png")); // NOI18N
        ProvjeraDugovanjaOP.setText("Pregled dugovanja");
        ProvjeraDugovanjaOP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(54, 89, 147), null, null));
        ProvjeraDugovanjaOP.setBorderPainted(false);
        ProvjeraDugovanjaOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvjeraDugovanjaOPActionPerformed(evt);
            }
        });

        OdjavaOP.setBackground(new java.awt.Color(255, 0, 0));
        OdjavaOP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OdjavaOP.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\User-Interface-Logout-icon.png")); // NOI18N
        OdjavaOP.setText("Odjavi se ");
        OdjavaOP.setActionCommand(" Nazad ");
        OdjavaOP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(54, 89, 147), null, null));
        OdjavaOP.setBorderPainted(false);
        OdjavaOP.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        OdjavaOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdjavaOPActionPerformed(evt);
            }
        });

        UkloniOP.setBackground(new java.awt.Color(7, 41, 78));
        UkloniOP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UkloniOP.setForeground(new java.awt.Color(255, 255, 255));
        UkloniOP.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\user-trash-full-icon.png")); // NOI18N
        UkloniOP.setText("Ukloni");
        UkloniOP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(54, 89, 147), null, null));
        UkloniOP.setBorderPainted(false);
        UkloniOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UkloniOPActionPerformed(evt);
            }
        });

        OcistiPolja.setBackground(new java.awt.Color(7, 41, 78));
        OcistiPolja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OcistiPolja.setForeground(new java.awt.Color(255, 255, 255));
        OcistiPolja.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\Clear-icon.png")); // NOI18N
        OcistiPolja.setText("Ocisti polja");
        OcistiPolja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(54, 89, 147), null, null));
        OcistiPolja.setBorderPainted(false);
        OcistiPolja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcistiPoljaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(OdjavaOP, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(NazadOP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(124, 124, 124)
                                        .addComponent(OcistiPolja, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(ProvjeraDugovanjaOP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ListajTabelu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(DodajS, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(UkloniOP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OdjavaOP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(ListajTabelu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DodajS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UkloniOP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ProvjeraDugovanjaOP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NazadOP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OcistiPolja, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NazadOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NazadOPActionPerformed
        new PocetnaSTDSL().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NazadOPActionPerformed

    private void ListajTabeluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListajTabeluActionPerformed
    
    
    String s="Select ID as ID_Prijave,Ime,Prezime,Indeks,Predmet,Datum from Prijava where Indeks=?"; 
    try{
            if(IndeksOP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Za izlistavanje je potrebno popuniti polje --Indeks--!","Upozorenje",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
                pst=con.prepareStatement(s);
                pst.setString(1,IndeksOP.getText()); 
                rs=pst.executeQuery();
                TabelaOP.setModel(DbUtils.resultSetToTableModel(rs));
            }
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Indeks nije pronadjen u bazi podataka!");
                    
        }
    }//GEN-LAST:event_ListajTabeluActionPerformed

    private void DodajSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajSActionPerformed
        int id=PredmetIR.getSelectedIndex();
        if(ImeOP.getText().isEmpty() || IDOP.getText().isEmpty() || IndeksOP.getText().isEmpty() || PrezimeOP.getText().isEmpty() || id==-1){
            JOptionPane.showMessageDialog(null,"Potrebno je popuniti sva polja prije unosa u bazu podataka!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String sqlSelect="select ID_P from Predmet where Naziv=?";
        try{
            con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
            pst=con.prepareStatement(sqlSelect);
            pst.setString(1,PredmetIR.getSelectedItem().toString());
            rs=pst.executeQuery();
            if(rs.next()){
                ID_PR=rs.getString("ID_P");
            }
           
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null,"Nisu pronadjene prijave u bazi!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
        }
        
        String sql="select ID_IR from Rokovi where ID_P=? and Datum=?";
        try{
            
            con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
            pst=con.prepareStatement(sql);
            pst.setString(1,ID_PR);
            pst.setString(2, DatumIR.getText());
            rs=pst.executeQuery();
            if(rs.next()){
            ID_IRK=rs.getString("ID_IR");
            brojac++;
            }
            else{
                JOptionPane.showMessageDialog(null,"Navedeni rok nije pronadjen!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
            }
           
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null,"Nisu pronadjene prijave u bazi!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
        }
            
            
            
        String s="Select ID from Prijava where Ime=? and Prezime=? and Indeks=? and Predmet=? and Datum=?";
            try{
            
                con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
                pst=con.prepareStatement(s);
                pst.setString(1,ImeOP.getText());
                pst.setString(2,PrezimeOP.getText());
                pst.setString(3,IndeksOP.getText());
                pst.setString(4,PredmetIR.getSelectedItem().toString());
                pst.setString(5,DatumIR.getText());
                rs=pst.executeQuery();
                while(rs.next()){
                    prijava++;
                }
                      
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
                    
        }
            
        if(brojac>0 && prijava==0){
            String str="insert into Prijava(Ime,Prezime,Indeks,Predmet,Datum,ID_IR)values(?,?,?,?,?,?)";
            
            try{
                con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
                pst=con.prepareStatement(str);
                
                pst.setString(1,ImeOP.getText());
                pst.setString(2,PrezimeOP.getText());
                pst.setString(3,IndeksOP.getText());
                pst.setString(4,PredmetIR.getSelectedItem().toString());
                pst.setString(5,DatumIR.getText());
                pst.setString(6,ID_IRK);                
                pst.execute();
                JOptionPane.showMessageDialog(null,"Uspjesno ste prijavili studenta!","Upozorenje",JOptionPane.INFORMATION_MESSAGE);
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(prijava>0){
            JOptionPane.showMessageDialog(null,"Student je vec prijavljen na ispitni rok iz selektovanog predmeta!","Upozorenje",JOptionPane.INFORMATION_MESSAGE);
        }
            
            }
        brojac=0;prijava=0;
    }//GEN-LAST:event_DodajSActionPerformed

    private void ProvjeraDugovanjaOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvjeraDugovanjaOPActionPerformed
        if(IDOP.getText().isEmpty()){
         JOptionPane.showMessageDialog(null,"Unesite br. indeksa prije provjere!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
          String sqlSelect="select ID_R from Rate where ID_S=?";
            try{
                    con=DriverManager.getConnection("jdbc:sqlserver://DESKTOP-0IO9IPQ:1433;databaseName=studentskaSluzba","admin","admin321");
                    pst=con.prepareStatement(sqlSelect);
                    pst.setString(1,IDOP.getText());
                    rs=pst.executeQuery();
                    while(rs.next())
                    {
                       trig++; 
                    }

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
               if(trig>0){
                   String str=IDOP.getText();
                   new PregledDugovanja(str).setVisible(true);
               }
               else{
                   JOptionPane.showMessageDialog(null, "ID studenta nije pronadjen u bazi podataka!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
               }
          
          trig=0;
        }
        
    }//GEN-LAST:event_ProvjeraDugovanjaOPActionPerformed

    private void OdjavaOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdjavaOPActionPerformed
        new LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OdjavaOPActionPerformed

    private void UkloniOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UkloniOPActionPerformed
     if(TabelaOP.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Potrebno je selektovati prijavu koju zelite izbrisati!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(TabelaOP.getSelectionModel().getSelectedItemsCount()>1){
            JOptionPane.showMessageDialog(null, "Moguce je selektovati samo jednu prijavu za brisanje!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(TabelaOP.getSelectionModel().getSelectedItemsCount()==1){
            
        int odg=JOptionPane.showConfirmDialog(null, "Da li zelite izbrisati selektovanu prijavu?","Potvrda",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(odg==0){
            DefaultTableModel model=(DefaultTableModel)TabelaOP.getModel();
            int indexR=TabelaOP.getSelectedRow();
            int ID_Prijave=(int)model.getValueAt(indexR, 0);
            String sql="delete from Prijava where ID='"+ID_Prijave+"'";
            try{
            con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
            pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Izbrisali ste selektovanu prijavu iz baze podataka","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
            model.removeRow(indexR);
            } 
        }
    }//GEN-LAST:event_UkloniOPActionPerformed

    private void PretragaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PretragaIDActionPerformed
        
        String s="Select Ime,Prezime,Br_indeksa from Student where ID_St=?";
        try{
            con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
            pst=con.prepareStatement(s);
            pst.setString(1,IDOP.getText());
            rs=pst.executeQuery();
           
            if(rs.next()){
                ImeOP.setText(rs.getString(1));
                PrezimeOP.setText(rs.getString(2));
                IndeksOP.setText(rs.getString(3));
                
            }
            else{
                JOptionPane.showMessageDialog(null,"ID studenta nije pronadjen u bazi podataka!","Upozorenje",JOptionPane.INFORMATION_MESSAGE);
            }
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
                    
        }
    }//GEN-LAST:event_PretragaIDActionPerformed

    private void PretragaIndeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PretragaIndeksActionPerformed
        String s="Select ID_St,Ime,Prezime from Student where Br_indeksa=?";
        try{
            con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
            pst=con.prepareStatement(s);
            pst.setString(1,IndeksOP.getText());
            rs=pst.executeQuery();
           if(rs.next()){
                IDOP.setText(rs.getString("ID_St"));
                ImeOP.setText(rs.getString(2));
                PrezimeOP.setText(rs.getString(3)); 
            }
           else{
               JOptionPane.showMessageDialog(null,"Indeks nije pronadjen u bazi podataka!","Upozorenje",JOptionPane.INFORMATION_MESSAGE);
           }
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_PretragaIndeksActionPerformed

    private void OcistiPoljaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcistiPoljaActionPerformed
        IDOP.setText("");
        ImeOP.setText("");
        PrezimeOP.setText("");
        IndeksOP.setText("");
        PredmetIR.setSelectedIndex(-1);
        
    }//GEN-LAST:event_OcistiPoljaActionPerformed
/***/
  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObradaPrijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObradaPrijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObradaPrijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObradaPrijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObradaPrijava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo DatumIR;
    private javax.swing.JButton DodajS;
    private javax.swing.JTextField IDOP;
    private javax.swing.JTextField ImeOP;
    private javax.swing.JTextField IndeksOP;
    private javax.swing.JButton ListajTabelu;
    private javax.swing.JButton NazadOP;
    private javax.swing.JButton OcistiPolja;
    private javax.swing.JButton OdjavaOP;
    private javax.swing.JComboBox<String> PredmetIR;
    private javax.swing.JButton PretragaID;
    private javax.swing.JButton PretragaIndeks;
    private javax.swing.JTextField PrezimeOP;
    private javax.swing.JButton ProvjeraDugovanjaOP;
    private javax.swing.JTable TabelaOP;
    private javax.swing.JButton UkloniOP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
