/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentska_sluzba;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sc21l
 */
public class PregledPrijavljenih extends javax.swing.JFrame {
    
    
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    String ID_P,ID_IR;
    int brojac=0;
    /**
     * Creates new form PregledPrijavljenih
     */
    public PregledPrijavljenih() {
        initComponents();
        this.setLocationRelativeTo(null);
        popuniPredmet();
        
        
        
    }
public void popuniPredmet(){
    
    String sqlSelect="select Naziv from Predmet";
    try{
            con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
            pst=con.prepareStatement(sqlSelect);
            rs=pst.executeQuery();
            while(rs.next())
            {
                PredmetIzvjestaj.addItem(rs.getString("Naziv"));
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PredmetIzvjestaj = new javax.swing.JComboBox<>();
        PretragaPrijavljenih = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DatumIzvjestaj = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        NazadIzvjestaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaIzvjestaj = new javax.swing.JTable();
        StampajIzvjestaj = new javax.swing.JButton();
        OdjavaIzvjestaj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Izvjestaj-Studentska sluzba");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "  Pregled ispitnog roka ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(7, 41, 78))); // NOI18N

        jLabel4.setText("Predmet");

        PredmetIzvjestaj.setMaximumRowCount(100);
        PredmetIzvjestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PredmetIzvjestajActionPerformed(evt);
            }
        });

        PretragaPrijavljenih.setBackground(new java.awt.Color(7, 41, 78));
        PretragaPrijavljenih.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PretragaPrijavljenih.setForeground(new java.awt.Color(255, 255, 255));
        PretragaPrijavljenih.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\zoom-search-2-icon.png")); // NOI18N
        PretragaPrijavljenih.setText(" Pretraga ");
        PretragaPrijavljenih.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(54, 89, 147), null, null));
        PretragaPrijavljenih.setBorderPainted(false);
        PretragaPrijavljenih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PretragaPrijavljenihActionPerformed(evt);
            }
        });

        jLabel3.setText("Datum");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PredmetIzvjestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatumIzvjestaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PretragaPrijavljenih, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PredmetIzvjestaj))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DatumIzvjestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(PretragaPrijavljenih, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));

        NazadIzvjestaj.setBackground(new java.awt.Color(7, 41, 78));
        NazadIzvjestaj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NazadIzvjestaj.setForeground(new java.awt.Color(255, 255, 255));
        NazadIzvjestaj.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\arrow-back-1-icon.png")); // NOI18N
        NazadIzvjestaj.setText(" Nazad");
        NazadIzvjestaj.setActionCommand("Nazad");
        NazadIzvjestaj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(54, 89, 147), null, null));
        NazadIzvjestaj.setBorderPainted(false);
        NazadIzvjestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NazadIzvjestajActionPerformed(evt);
            }
        });

        TabelaIzvjestaj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelaIzvjestaj.setSelectionBackground(new java.awt.Color(54, 89, 122));
        jScrollPane1.setViewportView(TabelaIzvjestaj);

        StampajIzvjestaj.setBackground(new java.awt.Color(7, 41, 78));
        StampajIzvjestaj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        StampajIzvjestaj.setForeground(new java.awt.Color(255, 255, 255));
        StampajIzvjestaj.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\print-icon.png")); // NOI18N
        StampajIzvjestaj.setText(" Stampanje");
        StampajIzvjestaj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(54, 89, 147), null, null));
        StampajIzvjestaj.setBorderPainted(false);
        StampajIzvjestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StampajIzvjestajActionPerformed(evt);
            }
        });

        OdjavaIzvjestaj.setBackground(new java.awt.Color(255, 0, 0));
        OdjavaIzvjestaj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OdjavaIzvjestaj.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\User-Interface-Logout-icon.png")); // NOI18N
        OdjavaIzvjestaj.setText("Odjavi se ");
        OdjavaIzvjestaj.setActionCommand(" Nazad ");
        OdjavaIzvjestaj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(54, 89, 147), null, null));
        OdjavaIzvjestaj.setBorderPainted(false);
        OdjavaIzvjestaj.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        OdjavaIzvjestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdjavaIzvjestajActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sc21l\\Documents\\NetBeansProjects\\Studentska_Sluzba\\LogoZaJavu\\apeironLogo.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OdjavaIzvjestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(NazadIzvjestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StampajIzvjestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(OdjavaIzvjestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StampajIzvjestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NazadIzvjestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel2.getAccessibleContext().setAccessibleName("  Izvjestaj o predmetu  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NazadIzvjestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NazadIzvjestajActionPerformed
        new PocetnaSTDSL().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NazadIzvjestajActionPerformed

    private void PretragaPrijavljenihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PretragaPrijavljenihActionPerformed
      TabelaIzvjestaj.removeAll();
        
        String sqlSelect="select ID_P from Predmet where Naziv=?";
        try{
            con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
            pst=con.prepareStatement(sqlSelect);
            pst.setString(1,PredmetIzvjestaj.getSelectedItem().toString());
            rs=pst.executeQuery();
            if(rs.next()){
                ID_P=rs.getString("ID_P");
            }
           
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null,"Nisu pronadjene prijave u bazi!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
        }
        
        String sql="select ID_IR from Rokovi where ID_P=? and Datum=?";
        try{
            
            con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
            pst=con.prepareStatement(sql);
            pst.setString(1,ID_P);
            pst.setString(2,DatumIzvjestaj.getText());
            rs=pst.executeQuery();
            if(rs.next()){
            ID_IR=rs.getString("ID_IR");
            brojac++;
            }
                       
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null,"Nisu pronadjene prijave u bazi!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
        }
      if(brojac>0){
        String s="select Ime+' '+Prezime as Student,Indeks from Prijava where ID_IR=? ";
        try{
            con=DriverManager.getConnection("jdbc:sqlserver://your-computer-name:port-number;databaseName=studentskaSluzba","admin","admin321");
            pst=con.prepareStatement(s);
            pst.setString(1,ID_IR);
            rs=pst.executeQuery(); 
            TabelaIzvjestaj.setModel(DbUtils.resultSetToTableModel(rs));
            DefaultTableModel model=(DefaultTableModel)TabelaIzvjestaj.getModel();            
            model.addColumn("Br.bodova ");
            model.addColumn("Zakljucna ocjena ");            
            
        }catch(Exception e){
            
        }  
      }
      else if(brojac==0){
                JOptionPane.showMessageDialog(null,"Navedeni rok nije pronadjen!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
      }
      
      brojac=0;ID_P="";ID_IR="";
           
    }//GEN-LAST:event_PretragaPrijavljenihActionPerformed


    private void StampajIzvjestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StampajIzvjestajActionPerformed
    int i=TabelaIzvjestaj.getRowCount();
    if(i>0){
      String s=TabelaIzvjestaj.getModel().getColumnName(0);
    if(s.equals("Title 1")){
        JOptionPane.showMessageDialog(null, "Moguce je stampati samo listu prijavljenih studenata!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
    }
    else{
    MessageFormat header=new MessageFormat(PredmetIzvjestaj.getSelectedItem().toString()+" "+DatumIzvjestaj.getText());
    MessageFormat footer=new MessageFormat("Apeiron 2019");
    try{
    
        TabelaIzvjestaj.setAutoResizeMode(WIDTH);
        TabelaIzvjestaj.print(JTable.PrintMode.FIT_WIDTH, header, footer);
       
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }  
    }
    else{
        JOptionPane.showMessageDialog(null, "Onemoguceno je stampanje prazne liste!","OBAVJESTENJE",JOptionPane.INFORMATION_MESSAGE);
    }
    
             
        
    }//GEN-LAST:event_StampajIzvjestajActionPerformed

    private void OdjavaIzvjestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdjavaIzvjestajActionPerformed
        new LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OdjavaIzvjestajActionPerformed

    private void PredmetIzvjestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PredmetIzvjestajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PredmetIzvjestajActionPerformed
/*
  */  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PregledPrijavljenih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PregledPrijavljenih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PregledPrijavljenih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PregledPrijavljenih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PregledPrijavljenih().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo DatumIzvjestaj;
    private javax.swing.JButton NazadIzvjestaj;
    private javax.swing.JButton OdjavaIzvjestaj;
    private javax.swing.JComboBox<String> PredmetIzvjestaj;
    private javax.swing.JButton PretragaPrijavljenih;
    private javax.swing.JButton StampajIzvjestaj;
    private javax.swing.JTable TabelaIzvjestaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
